/* ============================================================================
 * build.js — package Truss Lab for installation. Zero dependencies (Node 16+).
 *
 *   node tools/build.js
 *
 * Produces in dist/:
 *   TrussLab.html            one self-contained file (CSS + all JS inlined).
 *                            Double-click it: no server, no internet needed.
 *   TrussLab-Installer.zip   TrussLab.html + Windows/Mac/Linux installers +
 *                            plain-language INSTALL.txt, inside a TrussLab/ folder.
 * ==========================================================================*/
'use strict';

const fs = require('fs');
const path = require('path');
const zlib = require('zlib');

const ROOT = path.join(__dirname, '..');
const DIST = path.join(ROOT, 'dist');
const INST = path.join(ROOT, 'installer');
const read = (p) => fs.readFileSync(path.join(ROOT, p), 'utf8');

/* ---- 1. Inline everything into one HTML file --------------------------- */
function buildSingleFile() {
  let html = read('index.html');
  let styles = 0, scripts = 0;

  html = html.replace(/<link rel="stylesheet" href="([^"]+)"\s*\/?>/g, (_, href) => {
    styles++;
    return `<style>\n/* ${href} */\n${read(href)}\n</style>`;
  });

  html = html.replace(/<script src="([^"]+)"><\/script>/g, (_, src) => {
    scripts++;
    // A literal "</script" inside inlined code would end the tag early.
    const code = read(src).replace(/<\/script/gi, '<\\/script');
    return `<script>\n/* ${src} */\n${code}\n</script>`;
  });

  if (/<script src=|<link rel="stylesheet"/.test(html)) {
    throw new Error('build: an external script/stylesheet was left un-inlined');
  }
  html = html.replace('<head>', '<head>\n<!-- Truss Lab — single-file build. Generated by tools/build.js; edit the sources, not this file. -->');
  return { html, styles, scripts };
}

/* ---- 2. Minimal ZIP writer (deflate, UTF-8 names, Unix permissions) ---- */
const CRC_TABLE = (() => {
  const t = new Uint32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c >>> 0;
  }
  return t;
})();
function crc32(buf) {
  let c = 0xffffffff;
  for (let i = 0; i < buf.length; i++) c = CRC_TABLE[(c ^ buf[i]) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

function makeZip(entries) {
  const now = new Date();
  const dosTime = (now.getHours() << 11) | (now.getMinutes() << 5) | (now.getSeconds() >> 1);
  const dosDate = ((now.getFullYear() - 1980) << 9) | ((now.getMonth() + 1) << 5) | now.getDate();
  const parts = [], central = [];
  let offset = 0;
  for (const e of entries) {
    const name = Buffer.from(e.name, 'utf8');
    const data = Buffer.isBuffer(e.data) ? e.data : Buffer.from(e.data, 'utf8');
    const comp = zlib.deflateRawSync(data, { level: 9 });
    const crc = crc32(data);

    const lh = Buffer.alloc(30);
    lh.writeUInt32LE(0x04034b50, 0); lh.writeUInt16LE(20, 4); lh.writeUInt16LE(0x0800, 6);
    lh.writeUInt16LE(8, 8); lh.writeUInt16LE(dosTime, 10); lh.writeUInt16LE(dosDate, 12);
    lh.writeUInt32LE(crc, 14); lh.writeUInt32LE(comp.length, 18); lh.writeUInt32LE(data.length, 22);
    lh.writeUInt16LE(name.length, 26); lh.writeUInt16LE(0, 28);
    parts.push(lh, name, comp);

    const ch = Buffer.alloc(46);
    ch.writeUInt32LE(0x02014b50, 0); ch.writeUInt16LE((3 << 8) | 20, 4); // made by: Unix
    ch.writeUInt16LE(20, 6); ch.writeUInt16LE(0x0800, 8); ch.writeUInt16LE(8, 10);
    ch.writeUInt16LE(dosTime, 12); ch.writeUInt16LE(dosDate, 14); ch.writeUInt32LE(crc, 16);
    ch.writeUInt32LE(comp.length, 20); ch.writeUInt32LE(data.length, 24);
    ch.writeUInt16LE(name.length, 28); // extra, comment, disk, internal attrs = 0
    ch.writeUInt32LE(((0o100000 | (e.mode || 0o644)) << 16) >>> 0, 38); // regular file + perms
    ch.writeUInt32LE(offset, 42);
    central.push(ch, name);
    offset += lh.length + name.length + comp.length;
  }
  const cd = Buffer.concat(central);
  const end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(entries.length, 8); end.writeUInt16LE(entries.length, 10);
  end.writeUInt32LE(cd.length, 12); end.writeUInt32LE(offset, 16);
  return Buffer.concat([...parts, cd, end]);
}

/* ---- 3. Assemble ------------------------------------------------------- */
const crlf = (s) => s.replace(/\r?\n/g, '\r\n'); // Windows text files
const lf = (s) => s.replace(/\r\n/g, '\n'); // Unix scripts must be LF

function main() {
  fs.mkdirSync(DIST, { recursive: true });
  const { html, styles, scripts } = buildSingleFile();
  const htmlPath = path.join(DIST, 'TrussLab.html');
  fs.writeFileSync(htmlPath, html);

  const inst = (f) => fs.readFileSync(path.join(INST, f), 'utf8');
  const zip = makeZip([
    { name: 'TrussLab/TrussLab.html', data: html },
    { name: 'TrussLab/INSTALL.txt', data: crlf(inst('INSTALL.txt')) },
    { name: 'TrussLab/Install on Windows.bat', data: crlf(inst('Install on Windows.bat')) },
    { name: 'TrussLab/install-windows.ps1', data: crlf(inst('install-windows.ps1')) },
    { name: 'TrussLab/Install on Mac.command', data: lf(inst('Install on Mac.command')), mode: 0o755 },
    { name: 'TrussLab/install-linux.sh', data: lf(inst('install-linux.sh')), mode: 0o755 },
  ]);
  const zipPath = path.join(DIST, 'TrussLab-Installer.zip');
  fs.writeFileSync(zipPath, zip);

  const kb = (p) => (fs.statSync(p).size / 1024).toFixed(1) + ' KB';
  console.log(`Inlined ${styles} stylesheet(s) and ${scripts} script(s).`);
  console.log(`  ${path.relative(ROOT, htmlPath)}  ${kb(htmlPath)}`);
  console.log(`  ${path.relative(ROOT, zipPath)}  ${kb(zipPath)}`);
}

main();
