"""Pattern (skip) live loading (v0.19) — ETABS-style automatic live-load
patterning for continuous-beam design envelopes.

Continuous-beam RUNS are found geometrically: beams are grouped by the
LINE they lie on (same unit direction, same perpendicular offset, same
elevation) and CHAINED through shared endpoints; each maximal chain is
one run and its members get span indices 0, 1, 2, ... in order along the
line.  Isolated beams are single-span runs (span 0).

:func:`generate_pattern_live` then derives two skip patterns from a LIVE
pattern:

* ``<name>__ODD``  — the live member loads (member_loads, member_udls and
  thermal loads never move — only gravity-type member loads are live) on
  spans 0, 2, 4, ... of every run;
* ``<name>__EVEN`` — the loads on spans 1, 3, 5, ...

Loads that do not target a beam (nodal, story, area loads, loads on
columns/braces) CANNOT be span-classified; they are left out of the skip
patterns with a ``UserWarning`` (the all-spans case still carries them).
The classic checkerboard result: a span's midspan moment is maximized by
loading that span's parity only, its support moments by the complement —
the ``PATTERN-LL`` ENVELOPE combo generated by the API wraps
``1.2 D + 1.6 L(all | odd | even)`` (LRFD) so member design reads the
worst of the three automatically.

Adjacent-pair support patterns (the exact ACI 6.4.3 support arrangement)
are out of scope in v0.19 — documented; odd/even is the midspan-governing
classic subset.
"""

from __future__ import annotations

import math
import warnings
from typing import Dict, List, Tuple

from skyframe.core.model import (BuildingModel, LoadCase, LoadCombo,
                                 LoadPattern)

_TOL = 1e-6


def beam_spans(model: BuildingModel) -> Dict[str, int]:
    """{beam uid -> span index} along each continuous run (module doc).

    The span index is the beam's 0-based position along its run, ordered
    by projection onto the run direction.
    """
    beams = [m for m in model.members if m.kind == "beam"]
    lines: Dict[tuple, List] = {}
    for m in beams:
        dx = (m.pj[0] - m.pi[0], m.pj[1] - m.pi[1], m.pj[2] - m.pi[2])
        L = math.sqrt(sum(v * v for v in dx))
        u = tuple(v / L for v in dx)
        if u[0] < 0 or (abs(u[0]) < _TOL and u[1] < 0):
            u = tuple(-v for v in u)          # canonical direction
        # perpendicular offset: point minus its projection on u
        proj = sum(p * v for p, v in zip(m.pi, u))
        off = tuple(round(p - proj * v, 6) for p, v in zip(m.pi, u))
        key = (tuple(round(v, 6) for v in u), off)
        lines.setdefault(key, []).append((proj, m))
    spans: Dict[str, int] = {}
    for (u, _off), entries in lines.items():
        entries.sort(key=lambda e: e[0])
        # chain: consecutive beams sharing an endpoint stay in one run;
        # a gap starts a new run (span numbering restarts)
        idx = 0
        prev_end = None
        for proj, m in entries:
            end = proj + m.length
            if prev_end is not None and abs(proj - prev_end) > _TOL:
                idx = 0                        # disconnected -> new run
            spans[m.uid] = idx
            idx += 1
            prev_end = end
    return spans


def generate_pattern_live(model: BuildingModel, live_pattern: str
                          ) -> Tuple[str, str]:
    """Create ``<live>__ODD`` / ``<live>__EVEN`` skip patterns (module doc).

    Returns the two new pattern names.  Raises ``ValueError`` when the
    pattern is unknown, is not kind "live", or the derived names collide.
    Existing derived patterns are REPLACED (idempotent re-generation).
    """
    pat = model.patterns.get(live_pattern)
    if pat is None:
        raise ValueError(f"Unknown pattern {live_pattern!r}")
    if pat.kind != "live":
        raise ValueError(f"Pattern {live_pattern!r} has kind {pat.kind!r}; "
                         "pattern live loading needs a 'live' pattern")
    spans = beam_spans(model)
    odd_name, even_name = f"{live_pattern}__ODD", f"{live_pattern}__EVEN"
    odd = LoadPattern(odd_name, "live")
    even = LoadPattern(even_name, "live")
    skipped = 0
    for ml in pat.member_loads:
        span = spans.get(ml.member_uid)
        if span is None:
            skipped += 1
            continue
        (odd if span % 2 == 0 else even).member_loads.append(ml)
    for ul in pat.member_udls:
        span = spans.get(ul.member_uid)
        if span is None:
            skipped += 1
            continue
        (odd if span % 2 == 0 else even).member_udls.append(ul)
    non_member = (len(pat.nodal_loads) + len(pat.story_forces)
                  + len(pat.area_loads) + len(pat.thermal_loads)
                  + (1 if pat.self_weight_factor else 0))
    if skipped or non_member:
        warnings.warn(
            f"pattern live: {skipped} member loads not on beams and "
            f"{non_member} non-member loads (nodal/story/area/thermal/"
            "self-weight) cannot be span-classified; they remain only in "
            f"the all-spans pattern {live_pattern!r}", UserWarning)
    model.patterns[odd_name] = odd
    model.patterns[even_name] = even
    return odd_name, even_name


def pattern_live_envelope(model: BuildingModel, live_pattern: str,
                          *, dead_factor: float = 1.2,
                          live_factor: float = 1.6) -> str:
    """Create skip patterns + cases + the ``PATTERN-LL`` envelope combo.

    Cases ``PLL_ALL`` / ``PLL_ODD`` / ``PLL_EVEN`` are complete factored
    gravity sums (the DEAD-classified case's patterns at ``dead_factor``
    plus the respective live pattern at ``live_factor``) so the envelope
    combo — per-quantity min/max over the three cases at factor 1 — reads
    the worst pattern arrangement directly.  Requires a dead-classified
    case (same rule as the ASCE 7 combo generator).  Returns the combo
    name; regenerating replaces the previous cases/combo.
    """
    from skyframe.core.codes import _classify_cases
    dead_case, _, _, _ = _classify_cases(model)
    if dead_case is None:
        raise ValueError("pattern live: the model has no single-pattern "
                         "case with a 'dead' pattern (needed for the "
                         "factored envelope)")
    odd_name, even_name = generate_pattern_live(model, live_pattern)
    dead_patterns = model.cases[dead_case].patterns
    for cname, lp in (("PLL_ALL", live_pattern), ("PLL_ODD", odd_name),
                      ("PLL_EVEN", even_name)):
        pats = {p: dead_factor * f for p, f in dead_patterns.items()}
        pats[lp] = pats.get(lp, 0.0) + live_factor
        model.cases[cname] = LoadCase(cname, pats)
    model.combos["PATTERN-LL"] = LoadCombo(
        "PATTERN-LL", {"PLL_ALL": 1.0, "PLL_ODD": 1.0, "PLL_EVEN": 1.0},
        combo_type="envelope")
    return "PATTERN-LL"
