# -*- mode: python ; coding: utf-8 -*-
block_cipher = None

a = Analysis(
    ['app.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('assets', 'assets'),
    ],
    hiddenimports=[
        # Dash core
        'dash',
        'dash.dcc',
        'dash.html',
        'dash.dependencies',
        'dash._callback',
        'dash._grouping',
        'dash.exceptions',
        'dash_bootstrap_components',
        # Flask / Werkzeug
        'flask',
        'flask_compress',
        'werkzeug',
        'werkzeug.serving',
        'werkzeug.debug',
        'werkzeug.routing',
        'werkzeug.middleware',
        'werkzeug.middleware.proxy_fix',
        # Plotly
        'plotly',
        'plotly.graph_objects',
        'plotly.express',
        'plotly.subplots',
        'plotly.io',
        # Pandas / NumPy
        'pandas',
        'pandas._libs.tslibs.timedeltas',
        'pandas._libs.tslibs.np_datetime',
        'pandas._libs.tslibs.nattype',
        'pandas._libs.skiplist',
        'numpy',
        'numpy.core._methods',
        'numpy.lib.format',
        # openpyxl
        'openpyxl',
        'openpyxl.workbook',
        'openpyxl.worksheet',
        'openpyxl.styles',
        'openpyxl.writer.excel',
        'openpyxl.reader.excel',
        # Kaleido (PNG export)
        'kaleido',
        # comtypes (ETABS COM API — Windows only)
        'comtypes',
        'comtypes.client',
        'comtypes.server',
        'comtypes.typeinfo',
        # App modules — explicitly listed so PyInstaller bundles them
        'data_store',
        'etabs_connector',
        'shared.helpers',
        'features.overview.layout',
        'features.overview.callbacks',
        'features.plan_view.layout',
        'features.plan_view.callbacks',
        'features.story_drifts.layout',
        'features.story_drifts.callbacks',
        'features.story_forces.layout',
        'features.story_forces.callbacks',
        'features.base_reactions.layout',
        'features.base_reactions.callbacks',
        'features.frame_forces.layout',
        'features.frame_forces.callbacks',
        'features.modal.layout',
        'features.modal.callbacks',
        'features.displacements.layout',
        'features.displacements.callbacks',
        'features.load_patterns.layout',
        'features.load_patterns.callbacks',
        'features.torsion.layout',
        'features.torsion.callbacks',
        'features.statistics.layout',
        'features.statistics.callbacks',
        'features.heatmaps.layout',
        'features.heatmaps.callbacks',
        'features.code_checks.layout',
        'features.code_checks.callbacks',
        'features.outliers.layout',
        'features.outliers.callbacks',
        'features.correlation.layout',
        'features.correlation.callbacks',
        'features.scorecard.layout',
        'features.scorecard.callbacks',
        'layouts.main_layout',
        'layouts.header',
        'layouts.sidebar',
        'callbacks.connection',
        'callbacks.navigation',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='ETABS_Dashboard',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
